### ISSUE TITLE
程序无故退出且无法再次启动

### ISSUE THREAD

**Issue by nailu0** [kukume/kuku-bot#22]
昨晚还能正常使用，但今天早上突然发现机器人异常退出了，多次重启但是还是无法恢复。
系统是centos7，使用docker安装， qq是刚注册的小号， 机器在海外，无其他异常操作。
下面是容器的日志
`Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.icecreamqaq.yuq.YuQStarter$Companion.start(YuQStarter.kt:31)
        at com.icecreamqaq.yuq.YuQStarter.start(YuQStarter.kt)
        at me.kuku.yuq.Start.main(Start.java:39)
Caused by: java.lang.RuntimeException: 程序初始化失败！
        at com.IceCreamQAQ.Yu.loader.AppLoader.load(AppLoader.kt:98)
        at com.IceCreamQAQ.Yu.DefaultApp.start(DefaultApp.kt:38)
        ... 7 more
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo=)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at com.icecreamqaq.yuq.mirai.MiraiBot.init(MiraiBot.kt:145)
        at com.IceCreamQAQ.Yu.as.AsLoader.load(AsLoader.kt:42)
        at com.IceCreamQAQ.Yu.loader.AppLoader.load(AppLoader.kt:86)
        at com.IceCreamQAQ.Yu.DefaultApp.start(DefaultApp.kt:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.icecreamqaq.yuq.YuQStarter$Companion.start(YuQStarter.kt:31)
        at com.icecreamqaq.yuq.YuQStarter.start(YuQStarter.kt)
        at me.kuku.yuq.Start.main(Start.java:39)`

**Comment by kukume** [comment]
可能qq被冻结了，可能qq密码错误。mirai的提示有问题。

**Comment by nailu0** [comment]
是被冻结了。 刚刚处理完。请问下这个是无法避免的吗？有没有办法可以避免这个情况。 如果会经常发生，会很影响使用。

**Comment by kukume** [comment]
冻结是由腾讯冻结的啊，异地登录就可能会，挂几天就没事了
