### ISSUE TITLE
关于微博推送无法使用

### ISSUE THREAD

**Issue by MoAccelerator** [kukume/kuku-bot#33]
大佬您好，我使用您的机器人绑定微博 输入“wb 账号 密码”之后提示我账号需要验证 然后我输入了1 使用手机验证码验证，然后机器人就没反应了，后台输出消息如下↓↓↓
2021-02-11 18:26:24,892 [34mINFO [0;39m [36mc.i.y.RainBot@[DefaultDispatcher-worker-10][0;39m - 233(******) -> ([ "wb ***** *****" ])
2021-02-11 18:26:40,423 [1;31mERROR[0;39m [36mc.i.y.m.l.Network@[DefaultDispatcher-worker-10][0;39m - Exception in NetworkHandler
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
        at java.lang.Thread.run(Thread.java:748)
我尝试过使用魔法上网和关闭魔法上网，机器是华为云的云服务器，自己实在是没有能力解决这个问题，所以想请大佬帮我解惑，谢谢！

**Comment by kukume** [comment]
建议先使用微博绑定qq，然后使用`qqlogin qr`登录qq，在使用`qqquicklogin weibo`进行微博登录

**Comment by kukume** [comment]
或者使用`wb login`进行扫码登录

**Comment by MoAccelerator** [comment]
您好 参照了您提供的方法，我在微博绑定qq后输入qqlogin qr 
![image](https://user-images.githubusercontent.com/45995147/107634018-e0af8380-6ca3-11eb-9a17-9967d1d86b3f.png)
![image](https://user-images.githubusercontent.com/45995147/107634085-f8870780-6ca3-11eb-8373-47d324768091.png)
大多数时候是会报错，少部分时候正常输出二维码 但是
![image](https://user-images.githubusercontent.com/45995147/107634774-0b4e0c00-6ca5-11eb-803f-41751bc9b64e.png)
控制台会报错，我也不知道登上没有，然后我输入qqquicklogin weibo没反应，输入微博关注 链接 然后提示我网络或链接地址异常

**Comment by kukume** [comment]
我这边测试qq登录没有问题的是没有问题的。第一张图，是你的机器跟腾讯服务器连通性不好，第二张图是机器人发消息出现异常了，建议重启试试。
qqquicklogin weibo是需要在群里发送。
最后你试试微博扫码登录？`wblogin`

**Comment by kukume** [comment]
微博模拟电脑版搞不定，不知道有什么验证过不去，将换成手机版模拟登录。

**Comment by MoAccelerator** [comment]
([ "wblogin" ])
2021-02-11 23:31:44,806 [1;31mERROR[0;39m [36mc.i.y.m.l.Network@[DefaultDispatcher-worker-3][0;39m - Exception in NetworkHandler
java.lang.NullPointerException: null
        at me.kuku.yuq.controller.weibo.BindWeiboController.wbLoginByQr(BindWeiboController.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.icecreamqaq.yuq.controller.BotReflectMethodInvoker.invoke(BotReflectMethodInvoker.kt:226)
        at com.icecreamqaq.yuq.controller.BotActionInvoker.invoke$suspendImpl(BotActionInvoker.kt:61)
        at com.icecreamqaq.yuq.controller.BotActionInvoker.invoke(BotActionInvoker.kt)
        at com.IceCreamQAQ.Yu.controller.RouterImpl.invoke$suspendImpl(RouterImpl.kt:25)
        at com.IceCreamQAQ.Yu.controller.RouterImpl.invoke(RouterImpl.kt)
        at com.icecreamqaq.yuq.RainBot.todo$suspendImpl(RainBot.kt:100)
        at com.icecreamqaq.yuq.RainBot.todo(RainBot.kt)
        at com.icecreamqaq.yuq.RainBot.receiveFriendMessage$suspendImpl(RainBot.kt:67)
        at com.icecreamqaq.yuq.RainBot.receiveFriendMessage(RainBot.kt)
        at com.icecreamqaq.yuq.RainBot.receivePrivateMessage$suspendImpl(RainBot.kt:57)
        at com.icecreamqaq.yuq.RainBot.receivePrivateMessage(RainBot.kt)
        at com.icecreamqaq.yuq.mirai.MiraiBot$startBot$2.invokeSuspend(MiraiBot.kt:390)
        at com.icecreamqaq.yuq.mirai.MiraiBot$startBot$2.invoke(MiraiBot.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:394)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$1.invokeSuspend(EventChannel.kt:144)
        at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:49)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:161)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:49)
        at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:226)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.handlePacket(QQAndroidBotNetworkHandler.kt:613)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:566)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invoke(QQAndroidBotNetworkHandler.kt)
        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:273)
        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories$handleIncomingPacket$1.invokeSuspend(PacketFactory.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by MoAccelerator** [comment]
关于网络问题，我使用原版Mirai和Mirai_Lua这两款机器人都没有问题，我也不知道为什么一直是网络相关报错QAQ

**Comment by kukume** [comment]
你的wblogin是在私聊发送的？应该是要在群聊里面发送

**Comment by kukume** [comment]
新版的修复了，只限账号需要验证的号（使用密码登录完需要手机验证或者私信验证的），账号如果不需要验证的不能登录，我没有不需要验证的账号测试。
关于登录，扫码登录的都是需要在群聊发送的，密码登录的需要私聊发送的。
https://file.kuku.me/kuku-bot/2021-02-13/

**Comment by MoAccelerator** [comment]
感谢大佬，总算是登陆上了。
我还想请问一下订阅某个微博博主需要输入什么命令才可以自动推送呢？我查到了您以前的命令介绍网址https://u.iheit.com/kuku/bot/menu.html
但是我输入 微博监控 用户名 机器人并不会输出任何消息，后台看这段话也只是以消息的方式呈现，貌似并不是命令。然后我输入 查微博监控 提示我的订阅为空

**Comment by kukume** [comment]
https://api.kuku.me/menu#
那个一直没更新了。这个是菜单地址。
现在的指令应该是：`加微博监控 {用户名}`

**Comment by MoAccelerator** [comment]
谢谢您，我成功订阅上我单推的博主啦！非常感谢，最后我还想询问您一个问题，就是机器人有哪些功能是默认开启的呢？
是这样的，我这个号上同时挂着一个小栗子机器人，然后只是单独需要一个微博推送的功能，所以使用了您的机器人，我怕有哪些功能在默认开启的情况下跟我原来的机器人有些指令上的冲突。麻烦您了~

**Comment by kukume** [comment]
指令都在菜单里面写了，功能的话除了那种订阅推送都是可以直接通过指令响应的。
如果你发现有重复的指令响应，可以发送`加拦截 {指令前缀}`去让指令不会响应

**Comment by kukume** [comment]
加拦截的拦截对主人是无效的。那么可以用`加指令限制 {指令前缀} 0`去完全拦截

**Comment by MoAccelerator** [comment]
好的 我明白了，多谢大佬的解答！
